const mongoose=require('mongoose');

const Scghema=mongoose.Schema({
    Userid:{
        type:String
    },
    videoid:{
        type:String
    },
    video_url:{
        type:String
    },
    video_title:{
        type:String
    },
    description:{
        type:String
    },
    views_count:{
        type:String
    },
    published_date:{
        type:String
    },
    channel_logo:{
        type:String
    },
    channel_name:{
        type:String
    },
    subscribers:{
        type:String
    },
    category:{
        type:String
    },
    bucketlist:{
        type:Boolean
    },
    saved:{
        type:Boolean
    },
    liked:{
        type:String
    },
    thumbnail:{
        type:String
    },
    live:{
        type:Boolean
    },
    saved:{
        type:Boolean     
    }
})
const model=mongoose.model("saved",Scghema);
module.exports=model;